### ISSUE TITLE
Having trouble compiling new systemCommand

### ISSUE THREAD

**Issue by jason-instacart** [nerzh/swift-extensions-pack#1]
let process: Process = .init()   << Use of undeclared type 'Process'

I am on XCode 11.5

**Comment by nerzh** [comment]
thanks
maybe it was a ios project, I released the next release with a fix, please try again

https://github.com/nerzh/swift-extensions-pack/commit/d4bb172116167f798f71bcea4d0a6ac7f27a68e8

**Comment by nerzh** [comment]
@jason-instacart please, let me know if problem was not resolved
